version: "3.9"
services:
  web:
    build: .
    ports:
      - "80:5000"
    network_mode : "host"
      
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
    network_mode : "host"
    
    